afterbuy_sdk:
  afterbuy_global:
    accountToken: <your_account_token>
    partnerToken: <your_partner_token>
    endpointEnum: sandbox
    errorLanguageEnum: DE
  logger_interface:
  validatorBuilder:

when@test:
  afterbuy_sdk:
    afterbuy_global:
      endpointEnum: sandbox

when@prod:
  afterbuy_sdk:
    afterbuy_global:
      endpointEnum: prod